---

full_role_name: aws_ec2_base

ec2_default:
  assign_public_ip: yes

  # Ensure there are exactly this many servers matching the tags
  # specified in `tags`.
  exact_count: 1

  group: default

  # The default AMI is Debian 10 (Buster) amd64
  image: ami-00f4b9641119301bf

  instance_profile_name: ''

  # t3a.nano is cheaper but not free-tier eligible
  instance_type: t2.micro

  key_name: hostconf
  region: us-west-2
  tags:
    Name: new-default-instance
    AnsibleRole: "{{ full_role_name }}"
    ConfigManager: default
  volumes:
    - device_name: /dev/xvda
      volume_type: gp2
      volume_size: 8
      delete_on_termination: true
  vpc_subnet_id: ''
  wait: yes
